version: '3.8'

services:
  # Banco de Dados do Auth-Service
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  # Banco de Dados do Business-Service
  business-db:
    image: postgres:15-alpine
    container_name: business-db
    environment:
      POSTGRES_DB: business_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5433:5432" # Porta externa 5433 para não conflitar com o Auth
    volumes:
      - business_data:/var/lib/postgresql/data

  # Gerenciador Visual de Banco de Dados
  pgadmin:
    image: dpage/pgadmin4
    container_name: easypet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@easypet.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - auth-db
      - business-db

volumes:
  auth_data:
  business_data:
